name: Test workflow

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test Action Workflow (Job)
    permissions:
      # To write linting fixes
      contents: read
      # To write Super-linter status checks
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: "3.11"

      - name: Linter Step
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_YAML_PRETTIER: true

      - name: Run Printer
        run: python3 test.py


